SfCms_admin/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//
using SfCms_model;

namespace SfCms_admin.Controllers
{
    public class ImageController : Controller
    {
        private class_validation validation = new class_validation();

        public FileContentResult BlogImageLarge()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_blog_file blog_file = new class_blog_file(id, class_blog_file.image_type.large);

                return File(blog_file.content, blog_file.content_type);
            }
        }

        public FileContentResult BlogImageMedium()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_blog_file blog_file = new class_blog_file(id, class_blog_file.image_type.medium);

                return File(blog_file.content, blog_file.content_type);
            }
        }

        public FileContentResult BlogImageSmall()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_blog_file blog_file = new class_blog_file(id, class_blog_file.image_type.small);

                return File(blog_file.content, blog_file.content_type);
            }
        }

        public FileContentResult MentorImageLarge()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_mentor_file mentor_file = new class_mentor_file(class_mentor_file.search_type.mentor_id, class_mentor_file.image_type.large, id.ToString());

                return File(mentor_file.content, mentor_file.content_type);
            }
        }

        public FileContentResult MentorImageMedium()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_mentor_file mentor_file = new class_mentor_file(class_mentor_file.search_type.mentor_id, class_mentor_file.image_type.medium, id.ToString());

                return File(mentor_file.content, mentor_file.content_type);
            }
        }

        public FileContentResult MentorImageSmall()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_mentor_file mentor_file = new class_mentor_file(class_mentor_file.search_type.mentor_id, class_mentor_file.image_type.small, id.ToString());

                return File(mentor_file.content, mentor_file.content_type);
            }
        }

        public FileContentResult BeneficiaryImageLarge()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_beneficiary_file beneficiary_file = new class_beneficiary_file(class_beneficiary_file.search_type.beneficiary_id, class_beneficiary_file.image_type.large, id.ToString());

                return File(beneficiary_file.content, beneficiary_file.content_type);
            }
        }

        public FileContentResult BeneficiaryImageMedium()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_beneficiary_file beneficiary_file = new class_beneficiary_file(class_beneficiary_file.search_type.beneficiary_id, class_beneficiary_file.image_type.medium, id.ToString());

                return File(beneficiary_file.content, beneficiary_file.content_type);
            }
        }

        public FileContentResult BeneficiaryImageSmall()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_beneficiary_file beneficiary_file = new class_beneficiary_file(class_beneficiary_file.search_type.beneficiary_id, class_beneficiary_file.image_type.small, id.ToString());

                return File(beneficiary_file.content, beneficiary_file.content_type);
            }
        }

        public FileContentResult NewsImageLarge()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_news_file news_file = new class_news_file(class_news_file.search_type.news_id, class_news_file.image_type.large, id.ToString());

                return File(news_file.content, news_file.content_type);
            }
        }

        public FileContentResult NewsImageMedium()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_news_file news_file = new class_news_file(class_news_file.search_type.news_id, class_news_file.image_type.medium, id.ToString());

                return File(news_file.content, news_file.content_type);
            }
        }

        public FileContentResult NewsImageSmall()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_news_file news_file = new class_news_file(class_news_file.search_type.news_id, class_news_file.image_type.small, id.ToString());

                return File(news_file.content, news_file.content_type);
            }
        }
    }
}

SfCms_admin/Controllers/MentorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//
using SfCms_model;
using System.IO;
using System.Web.UI;
using ImageResizer;

namespace SfCms_admin.Controllers
{
    [AuthorizeSfCms_admin()]
    public class MentorController : Controller
    {
        //pattern
        private class_pattern pattern = new class_pattern();
        //settings
        private class_settings settings = new class_settings();
        //validation
        private class_validation validation = new class_validation();
        //menu
        private class_menu menu = new class_menu();
        //dictionary
        private class_dictionary dictionary = new class_dictionary();
        //mentor_dictionary
        private class_mentor_dictionary mentor_dictionary = new class_mentor_dictionary();

        public ActionResult Index()
        {
            //mentor
            class_mentor mentor = new class_mentor();
            mentor.generate_list(class_mentor.search_type.all, string.Empty);

            //mentor_file
            class_mentor_file mentor_file = new class_mentor_file();

            //project
            class_project project = new class_project();

            //pattern - begin
            this.pattern.settings = this.settings;
            this.pattern.menu = this.menu;
            this.pattern.dictionary = this.dictionary;
            this.pattern.mentor_dictionary = this.mentor_dictionary;
            this.pattern.mentor = mentor;
            this.pattern.mentor_file = mentor_file;
            this.pattern.project = project;
            //patern - end

            return View(this.pattern);
        }

        public ActionResult AddAsk()
        {
            //project
            class_project project = new class_project();
            project.generate_list(class_project.search_type.all, string.Empty);

            //pattern - begin
            this.pattern.settings = this.settings;
            this.pattern.menu = this.menu;
            this.pattern.dictionary = this.dictionary;
            this.pattern.mentor_dictionary = this.mentor_dictionary;
            this.pattern.project = project;
            //patern - end

            return View(this.pattern);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Add(FormCollection form, HttpPostedFileBase file)
        {
            class_sql sql = new class_sql();

            //form
            bool form_active = false;
            int form_project_id = 0;
            string form_name = string.Empty;
            string form_surname = string.Empty;
            string form_content = string.Empty;

            if (form["active"] == "true")
            {
                form_active = true;
            }
            form_project_id = int.Parse(form["project_id"]);
            form_name = form["name"];
            form_surname = form["surname"];
            form_content = form["content"];

            //mentor
            class_mentor mentor = new class_mentor(0);
            mentor.active = form_active;
            mentor.project_id = form_project_id;
            mentor.name = form_name;
            mentor.surname = form_surname;
            mentor.content = form_content;
            mentor.insert();

            //file
            if (file != null)
            {
                //mentor_file
                class_mentor_file mentor_file = new class_mentor_file();

                //image
                class_image image = new class_image(file.ContentType);

                //version
                foreach (var suffix in image.versions.Keys)
                {
                    file.InputStream.Seek(0, SeekOrigin.Begin);
                    image.stream_out = new System.IO.MemoryStream();
                    ImageBuilder.Current.Build(new ImageJob(file.InputStream, image.stream_out, new Instructions(image.versions[suffix]), false, true));
                    image.stream_out.Seek(0, SeekOrigin.Begin);

                    if (suffix == image.large)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        mentor_file.content_large = image.file_content;
                    }
                    else if (suffix == image.medium)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        mentor_file.content_medium = image.file_content;
                    }
                    else if (suffix == image.small)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        mentor_file.content_small = image.file_content;
                    }
                }

                mentor_file.mentor_id = mentor.id;
                mentor_file.content_type = file.ContentType;
                mentor_file.name = file.FileName;
                mentor_file.insert();
            }

            return RedirectToAction("Index");
        }

        public ActionResult EditAsk()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return RedirectToAction("HttpError404", "Error");
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                //mentor
                class_mentor mentor = new class_mentor(id);

                //mentor_file
                class_mentor_file mentor_file = new class_mentor_file(class_mentor_file.search_type.mentor_id, class_mentor_file.image_type.empty, mentor.id.ToString());

                //project
                class_project project = new class_project();
                project.generate_list(class_project.search_type.all, string.Empty);

                //pattern - begin
                this.pattern.settings = this.settings;
                this.pattern.menu = this.menu;
                this.pattern.dictionary = this.dictionary;
                this.pattern.mentor_dictionary = this.mentor_dictionary;
                this.pattern.mentor = mentor;
                this.pattern.mentor_file = mentor_file;
                this.pattern.project = project;
                //patern - end

                return View(this.pattern);
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FormCollection form, HttpPostedFileBase file)
        {
            class_sql sql = new class_sql();

            //form
            int form_id = 0;
            bool form_active = false;
            int form_project_id = 0;
            string form_name = string.Empty;
            string form_surname = string.Empty;
            string form_content = string.Empty;

            form_id = int.Parse(form["id"].ToString());
            if (form["active"] == "true")
            {
                form_active = true;
            }
            form_project_id = int.Parse(form["project_id"]);
            form_name = form["name"];
            form_surname = form["surname"];
            form_content = form["content"];

            //mentor
            class_mentor mentor = new class_mentor(form_id);
            mentor.active = form_active;
            mentor.project_id = form_project_id;
            mentor.name = form_name;
            mentor.surname = form_surname;
            mentor.content = form_content;
            mentor.update();

            //file
            if (file != null)
            {
                //mentor_file
                class_mentor_file mentor_file = new class_mentor_file(class_mentor_file.search_type.mentor_id, class_mentor_file.image_type.empty, mentor.id.ToString());
                mentor_file.delete();

                //image
                class_image image = new class_image(file.ContentType);

                //version
                foreach (var suffix in image.versions.Keys)
                {
                    file.InputStream.Seek(0, SeekOrigin.Begin);
                    image.stream_out = new System.IO.MemoryStream();
                    ImageBuilder.Current.Build(new ImageJob(file.InputStream, image.stream_out, new Instructions(image.versions[suffix]), false, true));
                    image.stream_out.Seek(0, SeekOrigin.Begin);

                    if (suffix == image.large)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        mentor_file.content_large = image.file_content;
                    }
                    else if (suffix == image.medium)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        mentor_file.content_medium = image.file_content;
                    }
                    else if (suffix == image.small)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];

SfCms_admin/Views/Mentor/DeleteAsk.cshtml
@model SfCms_model.class_pattern

@{
    Layout = "~/Views/Shared/_Layout_v1.6.cshtml";
}

<!-- begin page-header -->
<h1 class="page-header"><i class="fa fa-anchor"></i> @Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_8) <small>@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Delete)</small></h1>
<!-- end page-header -->
			
<!-- begin row -->
<div class="row">
	<!-- begin col-12 -->
	<div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
                <h4 class="panel-title"><i class="fa fa-trash-o"></i> @Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.DeleteAsk) @Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_9) @Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_1):@Model.mentor.id.ToString()</h4>
            </div>
            <div class="panel-body">
				<div class="note note-danger">
					<h4>@Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_7) @Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.DeleteAskHe)</h4>
					<p>
						@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.DeleteAccept) @Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_9)
                    </p>
				</div>
            </div>
            <div class="panel-body">
				<div class="media">
					<span class="media-left">
                        @if (@Model.mentor_file.id != 0)
                        {  
                            <img src="@Url.Action("MentorImageSmall", "Image", new { id = Model.mentor.id })" alt="" class="media-object" />
                        }
                    </span>
					<div class="media-body">
						<h4><i class="fa fa-cube"></i> @Model.project.name</h4>
                        <dl class="dl-horizontal">
                            <dt>@Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_1)</dt>
                            <dd>@Model.mentor.id.ToString()</dd>
                            <dt>@Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_2)</dt>
                            <dd>
                            @if(Model.mentor.active == true)
                            {
                                <span class="label label-success">@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Yes)</span>
                            }
                            else
                            {
                                <span class="label label-danger">@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.No)</span>
                            }
                            </dd>
                            <dt>@Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_5)</dt>
                            <dd>@Model.mentor.surname</dd>
                            <dt>@Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_4)</dt>
                            <dd>@Model.mentor.name</dd>
						</dl>
                        <p>@Html.Raw(Model.mentor.content)</p> 
					</div>
				</div>
			</div>
            <div class="panel-body panel-form">
                @using (Html.BeginForm("Delete", "Mentor", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal form-bordered" }))
                {
                    <fieldset>
                    <legend></legend>
                
                    <input type="hidden" id="id" name="id" value="@Model.mentor.id.ToString()"/>

                    <div class="form-group">
						<div class="col-md-12 col-sm-12">
                            <input type="submit" value="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Delete)" class="btn btn-danger active"/>
                            <a href="javascript:history.back(-1);" class="btn btn-success">
                                <i class="fa fa-arrow-circle-left"></i> @Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Return)
                            </a>
						</div>
					</div>

                    </fieldset>
                }
            </div>
        </div>
        <!-- end panel -->
	</div>
</div>
<!-- end row -->

SfCms_admin/Views/Mentor/EditAsk.cshtml
@model SfCms_model.class_pattern

@{
    Layout = "~/Views/Shared/_Layout_v1.6.cshtml";
}

<!-- begin page-header -->
<h1 class="page-header"><i class="fa fa-anchor"></i> @Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_8) <small>@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Edit)</small></h1>
<!-- end page-header -->
			
<!-- begin row -->
<div class="row">
	<!-- begin col-12 -->
	<div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
                <h4 class="panel-title"><i class="fa fa-plus-square"></i> @Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.EditAsk) @Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_9) @Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_1):@Model.mentor.id.ToString()</h4>
            </div>
            <div class="panel-body panel-form">
                <form action="@Url.Action("Edit","Mentor")" method="post" enctype = "multipart/form-data" class="form-horizontal form-bordered" data-parsley-validate="true" name="demo-form">
                    <input type="hidden" id="id" name="id" value="@Model.mentor.id.ToString()"/>
                    <div class="form-group">
                        <!-- active -->
					    <label class="control-label col-md-2 col-sm-2">@Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_2) :</label>
					    <div class="col-md-10 col-sm-10">
						    @{
                                string check = string.Empty;
                                if (Model.mentor.active == true)
                                {
                                    check = "checked";
                                }
                            }   
                            <div class="checkbox"><label><input type="checkbox" id="active" name="active" value="true" @check/>&nbsp</label></div>
					    </div>
				    </div>
                    <div class="form-group">
                        <!-- project_id -->
						<label class="control-label col-md-2 col-sm-2">@Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_3) *:</label>
						<div class="col-md-10 col-sm-10">
							<select class="form-control" id="select-required" name="project_id"  data-parsley-required="true" data-parsley-required-message="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.FieldRequired)">
								<option value="">@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Choose)</option>
								@for(var i = 0; i < Model.project.list.Count; i++)
                                {
                                    if(Model.mentor.project_id == @Model.project.list[i].id)
                                    {
                                        <option value="@Model.project.list[i].id.ToString()" selected="selected">@Model.project.list[i].name</option>
                                    }
                                    else
                                    {
                                        <option value="@Model.project.list[i].id.ToString()">@Model.project.list[i].name</option>
                                    }
                                }
							</select>
						</div>
					</div>
                    <div class="form-group">
                        <!-- surname -->
					    <label class="control-label col-md-2 col-sm-2">@Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_5) *:</label>
					    <div class="col-md-4 col-sm-4">
						    <input class="form-control" type="text" id="surname" name="surname" placeholder="@Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_5)" value="@Model.mentor.surname" maxlength="200" data-parsley-required="true" data-parsley-required-message="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.FieldRequired)"/>
					    </div>
                        <!-- name -->
                        <label class="control-label col-md-2 col-sm-2">@Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_4) *:</label>
                        <div class="col-md-4 col-sm-4">
                            <input class="form-control" type="text" id="name" name="name" placeholder="@Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_4)" value="@Model.mentor.name" maxlength="200" data-parsley-required="true" data-parsley-required-message="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.FieldRequired)"/>
                        </div>
				    </div>
                    <div class="form-group">
                        <!-- content -->
                        <label class="control-label col-md-2 col-sm-2" for="title">@Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_6) *:</label>
					    <div class="col-md-10 col-sm-10">
						    <textarea class="ckeditor" id="content" name="content" rows="20" maxlength="2000" data-parsley-required="true" data-parsley-required-message="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.FieldRequired)">@Model.mentor.content</textarea>
					    </div>
				    </div>  
                    <div class="form-group">
                        <!-- mentor_file -->
                        @if (Model.mentor_file.id == null)
                        {
                            <label class="control-label col-md-2 col-sm-2">@Model.mentor_dictionary.get_phrase(SfCms_model.class_mentor_dictionary.id.id_10) *:</label>
                        }
                        else
                        {
                            <label class="control-label col-md-2 col-sm-2">@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.PhotoEdit) (@Model.mentor_file.name)</label>                    
                        }
                        <div class="col-md-10 col-sm-10">    
                            <input type="file" class="btn" name="file" />
							@if (Model.mentor_file.id != 0)
                            {
								<div class="media"><img src="@Url.Action("MentorImageSmall", "Image", new { id = Model.mentor.id })" alt="" class="media-object" /></div>
							}
                        </div>
                    </div>
				    <div class="form-group">
					    <label class="control-label col-md-2 col-sm-2"></label>
					    <div class="col-md-10 col-sm-10">
                            <button type="submit" class="btn btn-primary">@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Save)</button>
                            <a href="javascript:history.back(-1);" class="btn btn-success">
                                <i class="fa fa-arrow-circle-left"></i> @Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Return)
                            </a>
					    </div>
				    </div>
                </form>
            </div>
        </div>
        <!-- end panel -->
	</div>
</div>
<!-- end row -->