SfCms_admin/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//
using SfCms_model;

namespace SfCms_admin.Controllers
{
    public class ImageController : Controller
    {
        private class_validation validation = new class_validation();

        public FileContentResult BlogImageLarge()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_blog_file blog_file = new class_blog_file(id, class_blog_file.image_type.large);

                return File(blog_file.content, blog_file.content_type);
            }
        }

        public FileContentResult BlogImageMedium()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_blog_file blog_file = new class_blog_file(id, class_blog_file.image_type.medium);

                return File(blog_file.content, blog_file.content_type);
            }
        }

        public FileContentResult BlogImageSmall()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_blog_file blog_file = new class_blog_file(id, class_blog_file.image_type.small);

                return File(blog_file.content, blog_file.content_type);
            }
        }

        public FileContentResult MentorImageLarge()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_mentor_file mentor_file = new class_mentor_file(class_mentor_file.search_type.mentor_id, class_mentor_file.image_type.large, id.ToString());

                return File(mentor_file.content, mentor_file.content_type);
            }
        }

        public FileContentResult MentorImageMedium()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_mentor_file mentor_file = new class_mentor_file(class_mentor_file.search_type.mentor_id, class_mentor_file.image_type.medium, id.ToString());

                return File(mentor_file.content, mentor_file.content_type);
            }
        }

        public FileContentResult MentorImageSmall()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_mentor_file mentor_file = new class_mentor_file(class_mentor_file.search_type.mentor_id, class_mentor_file.image_type.small, id.ToString());

                return File(mentor_file.content, mentor_file.content_type);
            }
        }

        public FileContentResult BeneficiaryImageLarge()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_beneficiary_file beneficiary_file = new class_beneficiary_file(class_beneficiary_file.search_type.beneficiary_id, class_beneficiary_file.image_type.large, id.ToString());

                return File(beneficiary_file.content, beneficiary_file.content_type);
            }
        }

        public FileContentResult BeneficiaryImageMedium()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_beneficiary_file beneficiary_file = new class_beneficiary_file(class_beneficiary_file.search_type.beneficiary_id, class_beneficiary_file.image_type.medium, id.ToString());

                return File(beneficiary_file.content, beneficiary_file.content_type);
            }
        }

        public FileContentResult BeneficiaryImageSmall()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_beneficiary_file beneficiary_file = new class_beneficiary_file(class_beneficiary_file.search_type.beneficiary_id, class_beneficiary_file.image_type.small, id.ToString());

                return File(beneficiary_file.content, beneficiary_file.content_type);
            }
        }

        public FileContentResult NewsImageLarge()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_news_file news_file = new class_news_file(class_news_file.search_type.news_id, class_news_file.image_type.large, id.ToString());

                return File(news_file.content, news_file.content_type);
            }
        }

        public FileContentResult NewsImageMedium()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_news_file news_file = new class_news_file(class_news_file.search_type.news_id, class_news_file.image_type.medium, id.ToString());

                return File(news_file.content, news_file.content_type);
            }
        }

        public FileContentResult NewsImageSmall()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_news_file news_file = new class_news_file(class_news_file.search_type.news_id, class_news_file.image_type.small, id.ToString());

                return File(news_file.content, news_file.content_type);
            }
        }
    }
}

SfCms_admin/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//
using SfCms_model;
using System.IO;
using System.Web.UI;
using ImageResizer;

namespace SfCms_admin.Controllers
{
	[AuthorizeSfCms_admin()]
    public class NewsController : Controller
    {
		//pattern
		private class_pattern pattern = new class_pattern();
		//settings
		private class_settings settings = new class_settings();
        //validation
        private class_validation validation = new class_validation();
		//menu
		private class_menu menu = new class_menu();
		//dictionary
		private class_dictionary dictionary = new class_dictionary();
		//news_dictionary
		private class_news_dictionary news_dictionary = new class_news_dictionary();

        public ActionResult Index()
        {
			//news
			class_news news = new class_news();
			news.generate_list(class_news.search_type.all, string.Empty);

			//pattern - begin
			this.pattern.settings = this.settings;
			this.pattern.menu = this.menu;
			this.pattern.dictionary = this.dictionary;
			this.pattern.news_dictionary = this.news_dictionary;
			this.pattern.news = news;
			//patern - end

			return View(this.pattern);
        }

		public ActionResult AddAsk()
		{
            //s
            class_s s = new class_s(class_s.dictionary.s_news);

			//pattern - begin
			this.pattern.settings = this.settings;
			this.pattern.menu = this.menu;
			this.pattern.dictionary = this.dictionary;
			this.pattern.news_dictionary = this.news_dictionary;
            this.pattern.s = s;
			//patern - end

			return View(this.pattern);
		}

		[HttpPost]
		[ValidateInput(false)]
        public ActionResult Add(FormCollection form, HttpPostedFileBase file)
		{
			class_sql sql = new class_sql();

			//form
			bool form_active = false;
			string form_title = string.Empty;
			string form_content = string.Empty;
			DateTime form_date_user = sql.data_default;
            int form_s_news_id = 0;
			string form_logo_link = string.Empty;

			if (form["active"] == "true")
			{
				form_active = true;
			}
			form_title = form["title"];
			form_content = form["content"];
			form_date_user = Convert.ToDateTime(form["date_user"]);
            form_s_news_id = int.Parse(form["s_news_id"]);
			form_logo_link = form["logo_link"];

			//news
			class_news news = new class_news(0);
			news.active = form_active;
			news.title = form_title;
			news.content = form_content;
			news.date_user = form_date_user;
            news.s_news_id = form_s_news_id;
			news.logo_link = form_logo_link;
			news.insert();

			//file
			if (file != null)
			{
                //news_file
                class_news_file news_file = new class_news_file();

                //image
                class_image image = new class_image(file.ContentType);

                //version
                foreach (var suffix in image.versions.Keys)
                {
                    file.InputStream.Seek(0, SeekOrigin.Begin);
                    image.stream_out = new System.IO.MemoryStream();
                    ImageBuilder.Current.Build(new ImageJob(file.InputStream, image.stream_out, new Instructions(image.versions[suffix]), false, true));
                    image.stream_out.Seek(0, SeekOrigin.Begin);

                    if (suffix == image.large)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        news_file.content_large = image.file_content;
                    }
                    else if (suffix == image.medium)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        news_file.content_medium = image.file_content;
                    }
                    else if (suffix == image.small)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        news_file.content_small = image.file_content;
                    }
                }

				news_file.news_id = news.id;
				news_file.content_type = file.ContentType;
				news_file.name = file.FileName;
				news_file.insert();
			}

            return RedirectToAction("Index");
		}

        public ActionResult EditAsk()
        {
			//id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return RedirectToAction("HttpError404", "Error");
            }
            else
            {
				int id = int.Parse(RouteData.Values["id"].ToString());

				//news
				class_news news = new class_news(id);

				//news_file
				class_news_file news_file = new class_news_file(class_news_file.search_type.news_id, class_news_file.image_type.empty, news.id.ToString());

                //s
                class_s s = new class_s(class_s.dictionary.s_news);

				//pattern - begin
				this.pattern.settings = this.settings;
				this.pattern.menu = this.menu;
				this.pattern.dictionary = this.dictionary;
				this.pattern.news_dictionary = this.news_dictionary;
				this.pattern.news = news;
				this.pattern.news_file = news_file;
                this.pattern.s = s;
				//patern - end

				return View(this.pattern);
            }
        }

        [HttpPost]
		[ValidateInput(false)]
        public ActionResult Edit(FormCollection form, HttpPostedFileBase file)
        {
			class_sql sql = new class_sql();

			//form
			int form_id = 0;
			bool form_active = false;
			string form_title = string.Empty;
			string form_content = string.Empty;
			DateTime form_date_user = sql.data_default;
            int form_s_news_id = 0;
			string form_logo_link = string.Empty;

			form_id = int.Parse(form["id"].ToString());
			if (form["active"] == "true")
			{
				form_active = true;
			}
			form_title = form["title"];
			form_content = form["content"];
			form_date_user = Convert.ToDateTime(form["date_user"]);
            form_s_news_id = int.Parse(form["s_news_id"]);
			form_logo_link = form["logo_link"];

			//news
			class_news news = new class_news(form_id);
			news.active = form_active;
			news.title = form_title;
			news.content = form_content;
			news.date_user = form_date_user;
            news.s_news_id = form_s_news_id;
			news.logo_link = form_logo_link;
			news.update();

			//file
			if (file != null)
			{
                //news_file
                class_news_file news_file = new class_news_file(class_news_file.search_type.news_id, class_news_file.image_type.empty, news.id.ToString());
                news_file.delete();

                //image
                class_image image = new class_image(file.ContentType);

                //version
                foreach (var suffix in image.versions.Keys)
                {
                    file.InputStream.Seek(0, SeekOrigin.Begin);
                    image.stream_out = new System.IO.MemoryStream();
                    ImageBuilder.Current.Build(new ImageJob(file.InputStream, image.stream_out, new Instructions(image.versions[suffix]), false, true));
                    image.stream_out.Seek(0, SeekOrigin.Begin);

                    if (suffix == image.large)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        news_file.content_large = image.file_content;
                    }
                    else if (suffix == image.medium)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        news_file.content_medium = image.file_content;
                    }
                    else if (suffix == image.small)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        news_file.content_small = image.file_content;
                    }
                }

				news_file.news_id = news.id;
				news_file.content_type = file.ContentType;
				news_file.name = file.FileName;
				news_file.insert();
			}

            return RedirectToAction("Index");
        }

        public ActionResult Show()
        {
			//id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return RedirectToAction("HttpError404", "Error");
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                //news
                class_news news = new class_news(id);

                //news_file
                class_news_file news_file = new class_news_file(class_news_file.search_type.news_id, class_news_file.image_type.empty, news.id.ToString());

                //pattern - begin
				this.pattern.settings = this.settings;
				this.pattern.menu = this.menu;
				this.pattern.dictionary = this.dictionary;
				this.pattern.news_dictionary = this.news_dictionary;
				this.pattern.news = news;
				this.pattern.news_file = news_file;
                //patern - end

SfCms_admin/Views/News/DeleteAsk.cshtml
@model SfCms_model.class_pattern

@{
    Layout = "~/Views/Shared/_Layout_v1.6.cshtml";
}

<!-- begin page-header -->
<h1 class="page-header"><i class="fa fa-newspaper-o"></i> @Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_9) <small>@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Delete)</small></h1>
<!-- end page-header -->
			
<!-- begin row -->
<div class="row">
	<!-- begin col-12 -->
	<div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
                <h4 class="panel-title"><i class="fa fa-trash-o"></i> @Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.DeleteAsk) @Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_8) @Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_1):@Model.news.id.ToString()</h4>
            </div>
            <div class="panel-body">
				<div class="note note-danger">
					<h4>@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_8) @Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.DeleteAskShe)</h4>
					<p>
						@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.DeleteAccept) @Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_9)
                    </p>
				</div>
            </div>
            <div class="panel-body">
				<div class="media">
					<span class="media-left">
						@if (Model.news_file.id != 0)
						{
							<img src="@Url.Action("NewsImageSmall", "Image", new { id = Model.news.id })" alt="" class="media-object" />
						}
                    </span>
					<div class="media-body">
						<h3 class="media-heading">@Model.news.date_user.ToShortDateString()</h3>
                        <h4>@Model.news.title</h4>
                        <dl class="dl-horizontal">
                            <dt>@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_1)</dt>
                            <dd>@Model.news.id.ToString()</dd>
                            <dt>@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_2)</dt>
                            <dd>
                            @if(Model.news.active == true)
                            {
                                <span class="label label-success">@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Yes)</span>
                            }
                            else
                            {
                                <span class="label label-danger">@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.No)</span>
                            }
                            </dd>
                            <dt>@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_12)</dt>
                            <dd>@Model.news.s_news_id_dictionary</dd>
                            <dt>@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_13)</dt>
                            <dd><a href="@Model.news.logo_link" target="_blank">@Model.news.logo_link</a></dd>
                            <dt>@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_5)</dt>
                            <dd>@Model.news.date_user.ToShortDateString()</dd>
                            <dt>@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_6)</dt>
                            <dd>@Model.news.date_admin.ToString()</dd>
						</dl>
                        <p>@Html.Raw(Model.news.content)</p> 
					</div>
				</div>
			</div>
            <div class="panel-body panel-form">
                @using (Html.BeginForm("Delete", "News", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal form-bordered" }))
                {
                    <fieldset>
                    <legend></legend>
                
                    <input type="hidden" id="id" name="id" value="@Model.news.id.ToString()"/>

                    <div class="form-group">
						<div class="col-md-12 col-sm-12">
                            <input type="submit" value="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Delete)" class="btn btn-danger active"/>
                            <a href="javascript:history.back(-1);" class="btn btn-success">
                                <i class="fa fa-arrow-circle-left"></i> @Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Return)
                            </a>
						</div>
					</div>

                    </fieldset>
                }
            </div>
        </div>
        <!-- end panel -->
	</div>
</div>
<!-- end row -->

SfCms_admin/Views/News/EditAsk.cshtml
@model SfCms_model.class_pattern

@{
    Layout = "~/Views/Shared/_Layout_v1.6.cshtml";
}

<!-- begin page-header -->
<h1 class="page-header"><i class="fa fa-newspaper-o"></i> @Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_9) <small>@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Edit)</small></h1>
<!-- end page-header -->
			
<!-- begin row -->
<div class="row">
	<!-- begin col-12 -->
	<div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>
                <h4 class="panel-title"><i class="fa fa-edit"></i> @Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.EditAsk) @Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_8) @Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_1):@Model.news.id.ToString()</h4>
            </div>
            <div class="panel-body panel-form">
                <form action="@Url.Action("Edit","News")" method="post" enctype = "multipart/form-data" class="form-horizontal form-bordered" data-parsley-validate="true" name="demo-form">
                    <input type="hidden" id="id" name="id" value="@Model.news.id.ToString()"/>
                    <div class="form-group">
                        <!-- active -->
						<label class="control-label col-md-2 col-sm-2">@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_2) :</label>
						<div class="col-md-2 col-sm-2">
							@{
                                string check = string.Empty;
                                if (Model.news.active == true)
                                {
                                    check = "checked";
                                }
                            }   
                            <div class="checkbox"><label><input type="checkbox" id="active" name="active" value="true" @check/>&nbsp</label></div>
						</div>
                         <!-- date_user -->
                        <label class="control-label col-md-2 col-sm-2">@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_5) *:</label>
                        <div class="col-md-2 col-sm-2">
                            <input type="text" class="form-control" id="datepicker-default" name="date_user" placeholder="@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_5)" value="@Model.news.date_user.ToShortDateString()" maxlength="10" data-parsley-required="true" data-parsley-required-message="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.FieldRequired)"/>
                        </div>
                        <!-- s_news_id -->
                        <label class="control-label col-md-2 col-sm-2">@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_12) *:</label>
                        <div class="col-md-2 col-sm-2">
                            <select class="form-control" id="s_news_id" name="s_news_id"  data-parsley-required="true" data-parsley-required-message="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.FieldRequired)">
								<option value="">@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Choose)</option>
								@for (var i = 0; i < Model.s.s_news.Count; i++)
                                {
                                    if(Model.news.s_news_id == @Model.s.s_news[i].id)
                                    {
                                        <option value="@Model.s.s_news[i].id.ToString()" selected="selected">@Model.s.s_news[i].name</option>
                                    }
                                    else
                                    {
                                        <option value="@Model.s.s_news[i].id.ToString()">@Model.s.s_news[i].name</option>
                                    }
                                }
							</select>
                        </div>
					</div>
                    <div class="form-group">
                        <!-- logo_link -->
						<label class="control-label col-md-2 col-sm-2" for="logo_link">@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_13) :</label>
						<div class="col-md-10 col-sm-10">
							<input class="form-control" type="text" id="logo_link" name="logo_link" placeholder="@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_13)" value="@Model.news.logo_link" maxlength="200" data-parsley-required="false" data-parsley-required-message="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.FieldRequired)"/>
						</div>
					</div>
                    <div class="form-group">
                        <!-- title -->
						<label class="control-label col-md-2 col-sm-2" for="title">@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_3) *:</label>
						<div class="col-md-10 col-sm-10">
							<input class="form-control" type="text" id="title" name="title" placeholder="@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_10)" value="@Model.news.title" maxlength="200" data-parsley-required="true" data-parsley-required-message="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.FieldRequired)"/>
						</div>
					</div>
                    <div class="form-group">
                        <!-- content -->
                        <label class="control-label col-md-2 col-sm-2" for="title">@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_4) *:</label>
						<div class="col-md-10 col-sm-10">
							<textarea class="ckeditor" id="content" name="content" rows="20" maxlength="4000" data-parsley-required="true" data-parsley-required-message="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.FieldRequired)">@Model.news.content</textarea>
						</div>
					</div>
                    <div class="form-group">
                        <!-- news_file -->  
                        @if (Model.news_file.id == 0)
                        {
                            <label class="control-label col-md-2 col-sm-2">@Model.news_dictionary.get_phrase(SfCms_model.class_news_dictionary.id.id_7) *:</label>
                        }
                        else
                        {
                            <label class="control-label col-md-2 col-sm-2">@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.PhotoEdit) (@Model.news_file.name)</label>                    
                        }
                        <div class="col-md-10 col-sm-10">    
                            <input type="file" class="btn" name="file" />
                            @if (Model.news_file.id != 0)
                            {
                                <div class="media"><img src="@Url.Action("NewsImageSmall", "Image", new { id = Model.news.id })" alt="" class="media-object" /></div>
                            }
                        </div>
                    </div>
					<div class="form-group">
						<label class="control-label col-md-2 col-sm-2"></label>
						<div class="col-md-10 col-sm-10">
                            
                            <button type="submit" class="btn btn-primary">@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Save)</button>
                            <a href="javascript:history.back(-1);" class="btn btn-success">
                                <i class="fa fa-arrow-circle-left"></i> @Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Return)
                            </a>
						</div>
					</div>

                </form>
            </div>
        </div>
        <!-- end panel -->
	</div>
</div>
<!-- end row -->