SfCms_admin/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//
using SfCms_model;

namespace SfCms_admin.Controllers
{
    public class ImageController : Controller
    {
        private class_validation validation = new class_validation();

        public FileContentResult BlogImageLarge()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_blog_file blog_file = new class_blog_file(id, class_blog_file.image_type.large);

                return File(blog_file.content, blog_file.content_type);
            }
        }

        public FileContentResult BlogImageMedium()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_blog_file blog_file = new class_blog_file(id, class_blog_file.image_type.medium);

                return File(blog_file.content, blog_file.content_type);
            }
        }

        public FileContentResult BlogImageSmall()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_blog_file blog_file = new class_blog_file(id, class_blog_file.image_type.small);

                return File(blog_file.content, blog_file.content_type);
            }
        }

        public FileContentResult MentorImageLarge()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_mentor_file mentor_file = new class_mentor_file(class_mentor_file.search_type.mentor_id, class_mentor_file.image_type.large, id.ToString());

                return File(mentor_file.content, mentor_file.content_type);
            }
        }

        public FileContentResult MentorImageMedium()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_mentor_file mentor_file = new class_mentor_file(class_mentor_file.search_type.mentor_id, class_mentor_file.image_type.medium, id.ToString());

                return File(mentor_file.content, mentor_file.content_type);
            }
        }

        public FileContentResult MentorImageSmall()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_mentor_file mentor_file = new class_mentor_file(class_mentor_file.search_type.mentor_id, class_mentor_file.image_type.small, id.ToString());

                return File(mentor_file.content, mentor_file.content_type);
            }
        }

        public FileContentResult BeneficiaryImageLarge()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_beneficiary_file beneficiary_file = new class_beneficiary_file(class_beneficiary_file.search_type.beneficiary_id, class_beneficiary_file.image_type.large, id.ToString());

                return File(beneficiary_file.content, beneficiary_file.content_type);
            }
        }

        public FileContentResult BeneficiaryImageMedium()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_beneficiary_file beneficiary_file = new class_beneficiary_file(class_beneficiary_file.search_type.beneficiary_id, class_beneficiary_file.image_type.medium, id.ToString());

                return File(beneficiary_file.content, beneficiary_file.content_type);
            }
        }

        public FileContentResult BeneficiaryImageSmall()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_beneficiary_file beneficiary_file = new class_beneficiary_file(class_beneficiary_file.search_type.beneficiary_id, class_beneficiary_file.image_type.small, id.ToString());

                return File(beneficiary_file.content, beneficiary_file.content_type);
            }
        }

        public FileContentResult NewsImageLarge()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_news_file news_file = new class_news_file(class_news_file.search_type.news_id, class_news_file.image_type.large, id.ToString());

                return File(news_file.content, news_file.content_type);
            }
        }

        public FileContentResult NewsImageMedium()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_news_file news_file = new class_news_file(class_news_file.search_type.news_id, class_news_file.image_type.medium, id.ToString());

                return File(news_file.content, news_file.content_type);
            }
        }

        public FileContentResult NewsImageSmall()
        {
            //id
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return null;
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_news_file news_file = new class_news_file(class_news_file.search_type.news_id, class_news_file.image_type.small, id.ToString());

                return File(news_file.content, news_file.content_type);
            }
        }
    }
}

SfCms_admin/Controllers/MobileAppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//
using SfCms_model;
using System.IO;
using System.Web.UI;
using ImageResizer;
using System.Security.Cryptography;
using System.Text;

namespace SfCms_admin.Controllers
{
    [AuthorizeSfCms_admin()]
    public class MobileAppController : Controller
    {
        //pattern
        private class_pattern pattern = new class_pattern();
        //settings
        private class_settings settings = new class_settings();
        //validation
        private class_validation validation = new class_validation();
        //menu
        private class_menu menu = new class_menu();
        //dictionary
        private class_dictionary dictionary = new class_dictionary();

        #region Sponsor

        public ActionResult Index()
        {
            class_sponsor sponsor = new class_sponsor();
            sponsor.generate_list_with_additional_data(class_sponsor.search_type.order_by_sequence, string.Empty);

            //pattern - begin
            this.pattern.settings = this.settings;
            this.pattern.menu = this.menu;
            this.pattern.dictionary = this.dictionary;
            this.pattern.sponsor = sponsor;
            //patern - end

            return View(this.pattern);
        }

        public ActionResult AddSponsorForm()
        {
            class_sponsor sponsor = new class_sponsor();
            sponsor.generate_list(class_sponsor.search_type.order_by_sequence, String.Empty);

            //pattern - begin
            this.pattern.settings = this.settings;
            this.pattern.menu = this.menu;
            this.pattern.dictionary = this.dictionary;
            this.pattern.start_seq = sponsor.list[0].sequence + 1;
            //patern - end

            return View(this.pattern);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddSponsor(FormCollection form, HttpPostedFileBase file)
        {
            class_sql sql = new class_sql();

            //form
            bool form_active = false;
            int form_sequence = 0;
            string form_color1 = string.Empty;
            string form_color2 = string.Empty;
            string form_name = string.Empty;
            decimal form_amount = 0;
            decimal form_rate = 0;

            if (form["active"] == "true")
            {
                form_active = true;
            }
            form_sequence = int.Parse(form["sequence"]);
            form_color1 = form["color1"];
            form_color2 = form["color2"];
            form_name = form["name"];
            form_amount = decimal.Parse(form["amount"]);
            form_rate = decimal.Parse(form["rate"]);

            string fileName = "";

            if (file != null)
            {
                try
                {
                    string savePath = Server.MapPath("/sponsor_logos/");

                    HashAlgorithm algorithm = SHA1.Create();
                    byte[] buffer_arr = algorithm.ComputeHash(Encoding.UTF8.GetBytes((int)DateTime.Now.Ticks + file.FileName));

                    StringBuilder string_builder = new StringBuilder();
                    foreach (byte buffer in buffer_arr)
                    {
                        string_builder.Append(buffer.ToString("X2"));
                    }
                    string[] ext_arr = file.FileName.Split('.');
                    fileName = string_builder.ToString().ToLower() + '.' + ext_arr[ext_arr.Length - 1];
                    string pathToCheck = savePath + fileName;
                    string tempfileName = "";
                    if (System.IO.File.Exists(pathToCheck))
                    {
                        int counter = 2;
                        while (System.IO.File.Exists(pathToCheck))
                        {
                            tempfileName = counter.ToString() + fileName;
                            pathToCheck = savePath + tempfileName;
                            counter++;
                        }

                        fileName = tempfileName;
                    }
                    else
                    {
                        // Notify the user that the file was saved successfully.
                    }
                    savePath += fileName;
                    file.SaveAs(savePath);
                }
                catch (Exception e)
                {

                }
            }

            //sponsor
            class_sponsor sponsor = new class_sponsor(0);
            sponsor.active = form_active;
            sponsor.sequence = form_sequence;
            sponsor.color1 = form_color1;
            sponsor.color2 = form_color2;
            sponsor.name = form_name;
            sponsor.amount = form_amount;
            sponsor.rate = form_rate;
            sponsor.logo_link = fileName;
            sponsor.insert();

            return RedirectToAction("Index");
        }
 
        public ActionResult EditSponsorForm(bool error = false)
        {
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return RedirectToAction("HttpError404", "Error");
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_sponsor sponsor = new class_sponsor(id);

                //pattern - begin
                this.pattern.settings = this.settings;
                this.pattern.menu = this.menu;
                this.pattern.dictionary = this.dictionary;
                this.pattern.sponsor = sponsor;
                this.pattern.err = error;

                //patern - end

                return View(this.pattern);
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditSponsor(FormCollection form, HttpPostedFileBase file)
        {
            class_sql sql = new class_sql();

            //form
            bool form_active = false;
            int form_sequence = 0;
            int form_id = 0;
            string form_color1 = string.Empty;
            string form_color2 = string.Empty;
            string form_name = string.Empty;
            decimal form_amount = 0;
            decimal form_rate = 0;

            if (form["active"] == "true")
            {
                form_active = true;
            }
            form_id = int.Parse(form["id"]);
            form_sequence = int.Parse(form["sequence"]);
            form_color1 = form["color1"];
            form_color2 = form["color2"];
            form_name = form["name"];
            form_amount = decimal.Parse(form["amount"]);
            form_rate = decimal.Parse(form["rate"]);

            class_sponsor sponsor_check = new class_sponsor();
            sponsor_check.generate_list(class_sponsor.search_type.search_by_seqence, form_sequence.ToString());
            if (sponsor_check.list.Count > 0 && sponsor_check.list[0].id != form_id)
            {
                return RedirectToAction("EditSponsorForm", new { id = form_id.ToString(), error = true });
            }
            else
            {
                //sponsor
                class_sponsor sponsor = new class_sponsor(form_id);
                sponsor.active = form_active;
                sponsor.sequence = form_sequence;
                sponsor.color1 = form_color1;
                sponsor.color2 = form_color2;
                sponsor.name = form_name;
                sponsor.amount = form_amount;
                sponsor.rate = form_rate;
           
                if (file != null)
                {
                    try
                    {
                        string savePath = Server.MapPath("/sponsor_logos/");
                        string[] up_file_arr = file.FileName.Split('.');
                        string[] db_file_arr = sponsor.logo_link.Split('.');
                        string fileName = db_file_arr[0] + "." + up_file_arr[up_file_arr.Length - 1];
                        string pathToCheck = savePath + fileName;
                        savePath += fileName;
                        file.SaveAs(savePath);
                        sponsor.logo_link = fileName;
                    }
                    catch (Exception e)
                    {

                    }
                }

                sponsor.update();

                return RedirectToAction("Index");
            }
        }

        public ActionResult DeleteSponsorForm(bool error = false)
        {
            if (!this.validation.czy_int(RouteData.Values["id"]))
            {
                return RedirectToAction("HttpError404", "Error");
            }
            else
            {
                int id = int.Parse(RouteData.Values["id"].ToString());

                class_sponsor_extended sponsor_extended = new class_sponsor_extended(id);

                //pattern - begin
                this.pattern.settings = this.settings;
                this.pattern.menu = this.menu;
                this.pattern.dictionary = this.dictionary;
                this.pattern.sponsor_extended = sponsor_extended;
                this.pattern.err = error;
                //patern - end

                return View(this.pattern);
            }
        }

        [HttpPost]
        public ActionResult DeleteSponsor(FormCollection form)
        {
            //form
            int form_id = 0;

            form_id = int.Parse(form["id"].ToString());

            //beneficiary
            class_sponsor_extended sponsor_extended = new class_sponsor_extended(form_id);

            if (!sponsor_extended.current_sponsor)
            {
                sponsor_extended.delete();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("DeleteSponsorForm", new { id = form_id.ToString(), error = true });
            }
        }

        #endregion Sponsor

        #region Runs

SfCms_admin/Views/MobileApp/AddSponsorForm.cshtml
@model SfCms_model.class_pattern

@{
    Layout = "~/Views/Shared/_Layout_v1.6.cshtml";
}

<!-- begin page-header -->
<h1 class="page-header"><i class="fa fa-anchor"></i> Sponsorzy <small>Dodaj</small></h1>
<!-- end page-header -->
			
<!-- begin row -->
<div class="row">
	<!-- begin col-12 -->
	<div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                </div>
                <h4 class="panel-title"><i class="fa fa-plus-square"></i> Dodajesz Sponsora</h4>
            </div>
            <div class="panel-body panel-form">
                <form action="@Url.Action("AddSponsor","MobileApp")" method="post" enctype = "multipart/form-data" class="form-horizontal form-bordered" data-parsley-validate="true" name="demo-form">
                    <div class="form-group">
                        <!-- active -->
					    <label class="control-label col-md-1 col-sm-1">Aktywny :</label>
					    <div class="col-md-2 col-sm-2">
						    <div class="checkbox"><label><input type="checkbox" id="active" name="active" value="true"/>&nbsp</label></div>
					    </div>
                        <!--sequence-->
					    <label class="control-label col-md-1 col-sm-1">Kolejność *:</label>
					    <div class="col-md-2 col-sm-2">
						    <select class="form-control" id="select-required" name="sequence"  data-parsley-required="true" data-parsley-required-message="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.FieldRequired)">
								@for (var i = Model.start_seq; i < (Model.start_seq + 5); i++)
                                {
                                     <option value="@i">@i</option>
                                }
							</select>
					    </div>
                        <!--color1-->
					    <label class="control-label col-md-1 col-sm-1">Kolor 1 *:</label>
					    <div class="col-md-2 col-sm-2">
						    <input class="form-control" type="text" id="color1" name="color1" placeholder="#ffffff" maxlength="7" data-parsley-required="true" data-parsley-required-message="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.FieldRequired)"/>  
					    </div>
                        <!--color2-->
					    <label class="control-label col-md-1 col-sm-1">Kolor 2 *:</label>
					    <div class="col-md-2 col-sm-2">
						    <input class="form-control" type="text" id="color2" name="color2" placeholder="#000000" maxlength="7" data-parsley-required="true" data-parsley-required-message="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.FieldRequired)"/>  
					    </div>
				    </div>
                    <div class="form-group">
                        <!-- name -->
                        <label class="control-label col-md-1 col-sm-1">Nazwa *:</label>
                        <div class="col-md-2 col-sm-2">
                            <input class="form-control" type="text" id="name" name="name" placeholder="" maxlength="200" data-parsley-required="true" data-parsley-required-message="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.FieldRequired)"/>
                        </div>
                        <!-- amount -->
                        <label class="control-label col-md-1 col-sm-1">Kwota (zł) *:</label>
                        <div class="col-md-2 col-sm-2">    
                            <input class="form-control" type="text" id="amount" name="amount" placeholder="" maxlength="8" data-parsley-required="true" data-parsley-required-message="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.FieldRequired)"/>
                        </div>
                        <!-- rate -->
                        <label class="control-label col-md-1 col-sm-1">Przelicznik (zł/km)*:</label>
                        <div class="col-md-2 col-sm-2">    
                            <input class="form-control" type="text" id="rate" name="rate" placeholder="" maxlength="5" data-parsley-required="true" data-parsley-required-message="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.FieldRequired)"/>
                        </div>
					</div>
                    <div class="form-group">
                        <!-- logo -->
                        <label class="control-label col-md-1 col-sm-1">Logo *:</label>
                        <div class="col-md-2 col-sm-2">    
                            <input type="file" class="btn" name="file" data-parsley-required="true" data-parsley-required-message="@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.FieldRequired)"/>
                        </div>
                    </div>
				    <div class="form-group">
					    <label class="control-label col-md-1 col-sm-1"></label>
					    <div class="col-md-10 col-sm-10">
                            <button type="submit" class="btn btn-primary">@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Add)</button>
                            <a href="javascript:history.back(-1);" class="btn btn-success">
                                <i class="fa fa-arrow-circle-left"></i> @Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Return)
                            </a>
					    </div>
				    </div>
                </form>
            </div>
        </div>
        <!-- end panel -->
	</div>
</div>
<!-- end row -->

SfCms_admin/Views/MobileApp/Index.cshtml
@model SfCms_model.class_pattern

@{
    Layout = "~/Views/Shared/_Layout_v1.6.cshtml";
}

<!-- begin page-header -->
<h1 class="page-header"><i class="fa fa-anchor"></i> Sponsorzy <small>Lista</small></h1>
<!-- end page-header -->
			
<!-- begin row -->
<div class="row">
	<!-- begin col-12 -->
	<div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
@*                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>*@
                </div>
                <h4 class="panel-title"><i class="fa fa-list-ul"></i></h4>
            </div>
            <div class="panel-body">
                <a href="@Url.Action("AddSponsorForm","MobileApp")" class="btn btn-success m-r-5 m-b-5"><i class="fa fa-plus-square"></i> @Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Add)</a>
                <div class="table-responsive">
                    <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th style="width: 30px;">Aktualny sponsor</th>
                            <!-- active -->
                            <th>Aktywny</th>
                            <!-- mentor -->
                            <th>Koleność</th>
                            <!-- project -->
                            <th>Nazwa</th>
                            <th style="text-align:center">Logo</th>
                            <th>Kolor 1</th>
                            <th>Kolor 2</th>                       
                            <th>Kwota</th>
                            <th>Przelicznik</th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @{bool next = true;}
                        @for (var i = 0; i < Model.sponsor.list_ext.Count; i++)
                        {
                            <tr @Html.Raw(next ? "class='next'" : "class='prev'")>
                                <td style="text-align:center;vertical-align:middle;">
                                    @if(Model.sponsor.list_ext[i].current_sponsor) 
                                    {
                                        @Html.Raw("<div id='active-dot'></div>");
                                        next = false;
                                    }
                                </td>
                                @if (@Model.sponsor.list_ext[i].active)
                                {
                                    <td><span class="label label-success">@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Yes)</span></td>
                                }
                                else
                                {
                                    <td><span class="label label-danger">@Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.No)</span></td>
                                }
                                <td>@Model.sponsor.list_ext[i].sequence</td>
                                <td>@Model.sponsor.list_ext[i].name</td>
                                <td style="text-align:center">
                                 @*@{
                                    Model.mentor_file.get_data(SfCms_model.class_mentor_file.search_type.mentor_id, SfCms_model.class_mentor_file.image_type.empty, Model.mentor.list[i].id.ToString());
                                    
                                    if (@Model.mentor_file.id != 0)
                                    {
                                        <div class="media media-sm"><img src="@Url.Action("MentorImageSmall", "Image", new { id = Model.mentor.list[i].id })" alt="" class="media-object" /></div>
                                    }
                                }*@
                                    <img style="max-height:200px;max-width:200px" src="~/sponsor_logos/@{@Model.sponsor.list_ext[i].logo_link}?@DateTime.Now.Ticks" />
                                </td>
                                <td>
                                    @Model.sponsor.list_ext[i].color1
                                    <div style="width:80px;height:30px;border:#e2e7eb solid 1px;background-color:@Model.sponsor.list_ext[i].color1"></div>
                                </td>
                                <td>
                                    @Model.sponsor.list_ext[i].color2
                                    <div style="width:80px;height:30px;border:#e2e7eb solid 1px;background-color:@Model.sponsor.list_ext[i].color2"></div>
                                </td>
                                <td>
                                    <dl class="dl-horizontal w60">
                                        <dt>Zebrano:</dt>
                                        <dd>@Model.sponsor.list_ext[i].gathered_amount zł</dd>
                                        <dt>Z kwoty:</dt>
                                        <dd>@Model.sponsor.list_ext[i].amount.ToString() zł</dd>
                                    </dl>
                                </td>
                                <td>
                                    @Model.sponsor.list_ext[i].rate.ToString() zł/km
                                </td>
                                <td><a href="@Url.Action("DeleteSponsorForm", "MobileApp", new { id = @Model.sponsor.list_ext[i].id.ToString() })" class="btn btn-danger btn-sm active m-r-5"><i class="fa fa-trash-o"></i> @Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Delete)</a></td>
                                <td><a href="@Url.Action("EditSponsorForm", "MobileApp", new { id = @Model.sponsor.list_ext[i].id.ToString() })" class="btn btn-primary btn-sm m-r-5"><i class="fa fa-edit"></i> @Model.dictionary.get_phrase(SfCms_model.class_dictionary.phrase.Edit)</a></td>
                            </tr>
                        }
                    </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- end panel -->
	</div>	  
</div>
<!-- end row -->