SfCms_user/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//
using SfCms_model;
using System.IO;
using System.Web.UI;
using ImageResizer;

namespace SfCms_user.Controllers
{
	[AuthorizeSfCms_beneficiary()]
    public class BlogController : Controller
    {
        //pattern
        private class_pattern pattern = new class_pattern();
        //validation
        private class_validation validation = new class_validation();
        //settings
        private class_settings settings = new class_settings();

        public ActionResult Index()
        {
            //menu
            class_menu menu = new class_menu();
            menu.generate_list();

			//beneficiary
			class_beneficiary beneficiary = new class_beneficiary(int.Parse(session.beneficiary_id));

			//beneficiary_file
			class_beneficiary_file beneficiary_file = new class_beneficiary_file();

			//project
			class_project project = new class_project(beneficiary.project_id);

            //blog
            class_blog blog = new class_blog();
            blog.generate_list(class_blog.search_type.beneficiary_id, beneficiary.id.ToString());

			//blog_file
			class_blog_file blog_file = new class_blog_file();

            //s_post
            class_s_post s_post = new class_s_post();          

            //pattern - begin
            this.pattern.menu = menu;
			this.pattern.beneficiary = beneficiary;
			this.pattern.beneficiary_file = beneficiary_file;
			this.pattern.project = project;
            this.pattern.blog = blog;
            this.pattern.blog_file = blog_file;
            this.pattern.s_post = s_post;
            //patern - end

            return View(this.pattern);
        }

        public ActionResult AddAsk()
        {
            //menu
            class_menu menu = new class_menu();
            menu.generate_list();

			//beneficiary
			class_beneficiary beneficiary = new class_beneficiary(int.Parse(session.beneficiary_id));

			//beneficiary_file
			class_beneficiary_file beneficiary_file = new class_beneficiary_file();

			//project
			class_project project = new class_project(beneficiary.project_id);

            //s
            class_s s = new class_s(class_s.dictionary.s_post);

            //pattern - begin
            this.pattern.menu = menu;
			this.pattern.beneficiary = beneficiary;
			this.pattern.beneficiary_file = beneficiary_file;
			this.pattern.project = project;
            this.pattern.s = s;
            //patern - end

            return View(this.pattern);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Add(FormCollection form, HttpPostedFileBase file_1, HttpPostedFileBase file_2, HttpPostedFileBase file_3, HttpPostedFileBase file_4, HttpPostedFileBase file_5)
        {
            class_sql sql = new class_sql();

            //form
            bool form_active = false;
            int form_s_post_id = 0;
            string form_title = string.Empty;
            string form_content = string.Empty;
            DateTime form_date_user = sql.data_default;
            string form_media_link = string.Empty;

            if (form["active"] == "true")
            {
                form_active = true;
            }
            form_s_post_id = int.Parse(form["s_post_id"]);
            form_title = form["title"];
            form_content = form["content"];
            form_date_user = Convert.ToDateTime(form["date_user"]);
            form_media_link = form["media_link"];

            //blog
            class_blog blog = new class_blog(0);
            blog.active = form_active;
            blog.beneficiary_id = int.Parse(session.beneficiary_id);
            blog.s_post_id = form_s_post_id;
            blog.title = form_title;
            blog.content = form_content;
            blog.date_user = form_date_user;
            blog.media_link = form_media_link;
            blog.insert();

            //file_1
            #region "file_1"
            if (file_1 != null)
            {
				string file_title = form["file_1_title"];
                int no = 1;

                //blog_file_1
                class_blog_file blog_file_1 = new class_blog_file();

                //image
                class_image image = new class_image(file_1.ContentType);

                //version
                foreach (var suffix in image.versions.Keys)
                {         
                    file_1.InputStream.Seek(0, SeekOrigin.Begin);
                    image.stream_out = new System.IO.MemoryStream();
                    ImageBuilder.Current.Build(new ImageJob(file_1.InputStream,image.stream_out,new Instructions(image.versions[suffix]), false, true));
                    image.stream_out.Seek(0, SeekOrigin.Begin);

                    if(suffix == image.large)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        blog_file_1.content_large = image.file_content;
                    }
                    else if (suffix == image.medium)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        blog_file_1.content_medium = image.file_content;
                    }
                    else if (suffix == image.small)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        blog_file_1.content_small = image.file_content;
                    }
                }

                blog_file_1.blog_id = blog.id;
                blog_file_1.no = no;
                blog_file_1.content_type = file_1.ContentType;
                blog_file_1.name = file_1.FileName;
                blog_file_1.title = file_title;
                blog_file_1.insert();
            }
            #endregion

            //file_2
            #region "file_2"
            if (file_2 != null)
            {
                string file_title = form["file_2_title"];
                int no = 2;

                //blog_file_2
                class_blog_file blog_file_2 = new class_blog_file();

                //image
                class_image image = new class_image(file_2.ContentType);

                //version
                foreach (var suffix in image.versions.Keys)
                {
                    file_2.InputStream.Seek(0, SeekOrigin.Begin);
                    image.stream_out = new System.IO.MemoryStream();
                    ImageBuilder.Current.Build(new ImageJob(file_2.InputStream, image.stream_out, new Instructions(image.versions[suffix]), false, true));
                    image.stream_out.Seek(0, SeekOrigin.Begin);

                    if (suffix == image.large)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        blog_file_2.content_large = image.file_content;
                    }
                    else if (suffix == image.medium)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        blog_file_2.content_medium = image.file_content;
                    }
                    else if (suffix == image.small)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

                        blog_file_2.content_small = image.file_content;
                    }
                }

                blog_file_2.blog_id = blog.id;
                blog_file_2.no = no;
                blog_file_2.content_type = file_1.ContentType;
                blog_file_2.name = file_2.FileName;
                blog_file_2.title = file_title;
                blog_file_2.insert();
            }
            #endregion

            //file_3
            #region "file_3"
            if (file_3 != null)
            {
                string file_title = form["file_3_title"];
                int no = 3;

                //blog_file_3
                class_blog_file blog_file_3 = new class_blog_file();

                //image
                class_image image = new class_image(file_3.ContentType);

                //version
                foreach (var suffix in image.versions.Keys)
                {
                    file_3.InputStream.Seek(0, SeekOrigin.Begin);
                    image.stream_out = new System.IO.MemoryStream();
                    ImageBuilder.Current.Build(new ImageJob(file_3.InputStream, image.stream_out, new Instructions(image.versions[suffix]), false, true));
                    image.stream_out.Seek(0, SeekOrigin.Begin);

                    if (suffix == image.large)
                    {
                        image.file_size = Convert.ToInt32(image.stream_out.Length.ToString());
                        image.file_content = new byte[image.file_size];
                        image.stream_out.Read(image.file_content, 0, image.file_size);

SfCms_user/Controllers/ProjektyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//
using SfCms_model;

namespace SfCms_user.Controllers
{
    public class ProjektyController : Controller
    {
        //pattern
        private class_pattern pattern = new class_pattern();
        //validation
        private class_validation validation = new class_validation();
        //tool
        private class_tool tool = new class_tool();

        //Index
        public ActionResult Index()
        {
            //menu
            class_menu menu = new class_menu();
            menu.generate_list();

			//id
			string id = string.Empty;

			//project
			class_project project = new class_project();

            //beneficiary
            class_beneficiary beneficiary = new class_beneficiary();

            //beneficiary_file
            class_beneficiary_file beneficiary_file = new class_beneficiary_file();

            //mentor
            class_mentor mentor = new class_mentor();

            //mentor_file
            class_mentor_file mentor_file = new class_mentor_file();

            //paylane
            class_paylane paylane = new class_paylane();

            //blog
            class_blog blog = new class_blog();

            //blog_file
            class_blog_file blog_file = new class_blog_file();

            //s_post
            class_s_post s_post = new class_s_post();

			if (this.validation.czy_string_not_empty(RouteData.Values["id"]))
			{
				id = RouteData.Values["id"].ToString();

				project.generate_list(class_project.search_type.name, id);

                if (project.list.Count == 1)
                {
                    //project
                    project = project.list[0];

					//mentor
					mentor.generate_list(class_mentor.search_type.project_id, project.id.ToString());

                    //beneficiary
                    beneficiary.generate_list(class_beneficiary.search_type.project_id, project.id.ToString());

                    //paylane
                    paylane.generate_list(class_paylane.search_type.donor_all, project.id.ToString());
                }
			}
			else
			{
				
			}

            int support_tens = project.support % 100, support_singles = support_tens % 10;
            string str_osoby = "osób", str_wsparcie = "wsparło";

            if (project.support == 1)
            {
                str_osoby = "osoba";
                str_wsparcie = "wsparła";
            }
            else if (support_tens > 5 && support_tens < 21)
            {
                str_osoby = "osób";
                str_wsparcie = "wsparło";
            }
            else if (support_singles >= 2 && support_singles <= 4)
            {
                str_osoby = "osoby";
                str_wsparcie = "wsparły";
            }
            else if (support_singles == 1 || (support_singles >= 5 && support_singles <= 9))
            {
                str_osoby = "osób";
                str_wsparcie = "wsparło";
            }

            //pattern - begin
            this.pattern.menu = menu;
            this.pattern.project = project;
            this.pattern.beneficiary = beneficiary;
            this.pattern.mentor = mentor;
            this.pattern.paylane = paylane;
            this.pattern.beneficiary_file = beneficiary_file;
            this.pattern.mentor_file = mentor_file;
            this.pattern.blog = blog;
            this.pattern.blog_file = blog_file;
            this.pattern.s_post = s_post;
            this.pattern.tool = tool;

            this.pattern.str_osoby = str_osoby;
            this.pattern.str_wsparcie = str_wsparcie;
            //patern - end

            return View(this.pattern);
        }
    }
}

SfCms_user/Views/Shared/Blog.cshtml
@model SfCms_model.class_pattern

<!-- GLOBAL -->
@{
    string controller = ViewContext.RouteData.GetRequiredString("controller").ToLower();
    string action = ViewContext.RouteData.GetRequiredString("action").ToLower();
}
<!-- END GLOBAL -->

<!-- TITLE -->
@{
    string title = string.Empty;

    //projekty
    if (controller == "projekty")
    {
        if (Model.project.active)
        {
            //beneficiary
            for (var i = 0; i < Model.beneficiary.list.Count(); i++)
            {
                if (Model.beneficiary.list[i].active)
                {
                    title += Model.beneficiary.list[i].name + " ";
                }
            }

            //project
            title += "- " + Model.project.name;
        }
    }
}
<!-- TITLE -->

<!DOCTYPE html>
<html style="height:100%" lang="pl">
<head>
    <title>@title - Program Mentor</title>
    <meta content="@title | Mentor - gdański program stypendialny" name="description">
    <meta property="og:title" content="@title - Program Mentor">

    @{Html.RenderPartial("Header");}

    <link rel="stylesheet" type="text/css" href="~/assets/css/style_blog.css">
    <link rel="stylesheet" type="text/css" href="~/assets/css/style_footer.css" />

    <style type="text/css">
    .photo-wrapper {
        border: 5px solid #FFFFFF;
        width: 60px;
        height: 60px;
        background-position: center;
        background-size: cover;
        border-radius: 50%;  
        float: left;
        margin-left: 40px;
        margin-top: 22px;
    }
        #user-name {
            float:left;
            margin-top: 40px;
            margin-left: 10px;
        }
    </style>
</head>
<body style="height: 100%;box-sizing: border-box;">
    <div id="header">
        <div class="wrapper">
            @{
                Model.menu.get_data(1);
                Model.beneficiary_file.get_data(SfCms_model.class_beneficiary_file.search_type.beneficiary_id, SfCms_model.class_beneficiary_file.image_type.empty, Model.beneficiary.id.ToString());							
            }
            <a href="@Url.Action(Model.menu.action, Model.menu.controller)" style="float:left">
                <img id="m_logo" src="~/assets/img/logo-login.png" alt="Logo Mentor" />
            </a>
            
            @if (Model.beneficiary_file.id != 0)
            {
                <div class="photo-wrapper" style="background-image:url('@Url.Action("BeneficiaryImageSmall", "Image", new { id = Model.beneficiary.id })')"></div>               
            }
            <div id="user-name">@Model.beneficiary.name<br/>@Model.beneficiary.surname</div> 
            <div class="menu">

                @if(@Model.beneficiary.yt_link.Length > 1) {
                    <a href="@Model.beneficiary.yt_link" target="_blank">Zobacz kanał Youtube</a>
                }
                <a href="@Url.Action("Index", "Projekty", new { id = @Model.project.name })" target="_blank">Zobacz Blog</a>
                
                @if (action == "index")
                {
                    <a href="@Url.Action("AddAsk", "Blog")"><span>+</span> Dodaj post</a>
                }
                else
                {
                    <a href="@Url.Action("Index", "Blog")"><img style="margin-right:10px" src="~/assets/img/icon_lines.png" />Lista postów</a>
                }
               
                <a href="@Url.Action("LogOff", "Account")" class="login-btn"><span>Wyloguj</span></a>
            </div>
        </div>
    </div>

    <div style="position: relative;padding-bottom: 159px;min-height: 100%;box-sizing: border-box;">

        @RenderBody()

        <div id="footer-wrapper" style="position:absolute">
            <div class="gray-bar bg-gray1" style="height: 15px"></div>
            <footer id="footer">
                <div class="bg-gray3" style="height: 100px">
                    <div class="wrapper">
                    </div>
                    <div style="clear: both"></div>
                </div>
                <div class="bg-gray2" style="background-color: #ffffff;">
                    <div class="wrapper">
                        <span>Wszelkie prawa zastrzeżone © 2015</span>
                        <a href="http://www.quellio.com" target="_blank">
                            <img src="~/assets/img/logos/Quellio_small.png" alt="Quellio" />
                        </a>
                        <div style="clear: both"></div>
                    </div>
                </div>
                <div class="bg-gray3"></div>
            </footer>
        </div>

    </div>

    <script type="text/javascript">
        var shadowVisible = false,
            header;
        $(document).ready(function () {
            header = $("#header");
            $(window).scroll(toggleShadow);
            $(window).load(positionFooter);
            $(window).resize(positionFooter);
        });

        function positionFooter() {
            //h4 = window.innerHeight;
            //hs = $('#page-content').outerHeight(true) + $('#footer-wrapper').height() + $("#header").height();
            //if (hs > h4)
            //    $('body').addClass('high');
            //else
            //    $('body').removeClass('high');
        }

        function toggleShadow() {
            if (!shadowVisible) {
                header.addClass("header-shadow");
                shadowVisible = true;
            } else if ($(window).scrollTop() == 0) {
                header.removeClass("header-shadow");
                shadowVisible = false;
            }
        }
    </script>
</body>
</html>

SfCms_user/Views/Shared/Header.cshtml
@model SfCms_model.class_pattern

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta content="IE=edge" http-equiv="X-UA-Compatible">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">

<!--<meta name="robots" content="index,all,follow">-->
<meta name="distribution" content="global">
<meta name="author" content="Quellio">

<meta property="og:site_name" content="Mentor - gdański program stypendialny">
<meta property="og:description" content="Mentor - gdański program stypendialny">
<meta property="og:image" content="~/assets/favicons/mstile-310x310.png">
<meta property="og:url" content="http://www.program-mentor.pl/">
<meta property="og:type" content="organization">

<link rel="apple-touch-icon" sizes="57x57" href="~/assets/favicons/apple-touch-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="~/assets/favicons/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="~/assets/favicons/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="~/assets/favicons/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="~/assets/favicons/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="~/assets/favicons/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="~/assets/favicons/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="~/assets/favicons/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="~/assets/favicons/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" href="~/assets/favicons/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="~/assets/favicons/favicon-194x194.png" sizes="194x194">
<link rel="icon" type="image/png" href="~/assets/favicons/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="~/assets/favicons/android-chrome-192x192.png" sizes="192x192">
<link rel="icon" type="image/png" href="~/assets/favicons/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="~/assets/favicons/manifest.json">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-TileImage" content="~/assets/favicons/mstile-144x144.png">
<meta name="theme-color" content="#ffffff">

<link rel="stylesheet" type="text/css" href="~/assets/css/reset.css">
<link rel="stylesheet" type="text/css" href="~/assets/css/common.css">
<link rel="stylesheet" type="text/css" href="~/assets/css/jquery.fancybox.css" />

<script src="~/assets/bootstrap/jquery-1.10.2.min.js"></script>
<script type="text/javascript">
    var rv = 10;
    if (navigator.appName == 'Microsoft Internet Explorer') {
        var ua = navigator.userAgent;
        var re = new RegExp("MSIE ([0-9]{1,}[\.0-9]{0,})");
        if (re.exec(ua) != null)
            rv = parseFloat(RegExp.$1);
    }
    if (!navigator.userAgent.toLowerCase().match(/(iphone|windows phone|android)/)) {
        if (rv > 8) {
            var fileref = document.createElement("script");
            fileref.setAttribute("type", "text/javascript");
            fileref.setAttribute("src", "@SfCms_user.StaticMethods.getBaseUrl(Url.Content("~"))/assets/js/jquery.smoothwheel.js");
            document.getElementsByTagName("head")[0].appendChild(fileref);
        }
    }
</script>
<script>
    (function (i, s, o, g, r, a, m) {
        i["GoogleAnalyticsObject"] = r; i[r] = i[r] || function () {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
        m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
    })(window, document, "script", "//www.google-analytics.com/analytics.js", "ga");

    ga("create", "UA-56946436-4", "auto");
    ga("send", "pageview");
</script>

SfCms_user/Views/Shared/Login.cshtml
@model SfCms_model.class_pattern

<!-- GLOBAL -->
@{
    string controller = ViewContext.RouteData.GetRequiredString("controller").ToLower();
    string action = ViewContext.RouteData.GetRequiredString("action").ToLower();
}
<!-- END GLOBAL -->

<!-- TITLE -->
@{
    string title = string.Empty;

    //projekty
    if (controller == "projekty")
    {
        if (Model.project.active)
        {
            //beneficiary
            for (var i = 0; i < Model.beneficiary.list.Count(); i++)
            {
                if (Model.beneficiary.list[i].active)
                {
                    title += Model.beneficiary.list[i].name + " ";
                }
            }

            //project
            title += "- " + Model.project.name;
        }
    }
}
<!-- TITLE -->

<!DOCTYPE html>
<html lang="pl">
<head>
    <title>@title - Program Mentor</title>
    <meta content="@title | Mentor - gdański program stypendialny" name="description">
    <meta property="og:title" content="@title - Program Mentor">

    @{Html.RenderPartial("Header");}

    <style type="text/css">
        
    </style>

</head>
<body>

    @RenderBody()

</body>
</html>

SfCms_user/Views/Shared/Main.cshtml
@model SfCms_model.class_pattern

<!DOCTYPE html>
<html lang="pl">
<head>
    <title>Mentor - Gdański Program Stypendialny</title>
    <meta content="Mentor - gdański program stypendialny" name="description">
    <meta property="og:title" content="Mentor - Gdański Program Stypendialny">

    @{Html.RenderPartial("Header");}

    <link rel="stylesheet" href="~/assets/css/style_main.css" type="text/css">
    <link rel="stylesheet" href="~/assets/css/style_main_media.css" type="text/css">

    <script>
        var style;
        if (style !== undefined)
            style.remove();
        var h = window.innerHeight - (window.innerWidth < 960 ? 75 : 90);
        h = h < 400 ? 400 : h;
        style = $("<style />", {
            id: 'pageHeightStyle',
            type: 'text/css',
            html: ".page {height:" + h + "px}"
        });
        style.appendTo('head');
    </script>
</head>
<body>

    @RenderBody()

    <script type="text/javascript">
        var $pages = document.getElementsByClassName("page");
        for(i = 0; i < $pages.length; i++) {
            var $wrapper = $pages[i].getElementsByClassName("wrapper");
            var a1 = 0, a2 = 0, a3 = 0, a4 = 0, a5 = 0;
            if ($wrapper.length > 0) {
                var $image = $wrapper[0].getElementsByClassName("image");
                var $image_column = $wrapper[0].getElementsByClassName("image-column");

                if ($image.length > 0) {
                    a1 = $image[0].naturalHeight || 0;
                    a2 = parseInt($image[0].style.paddingTop) || 0;
                }
                if ($image_column.length > 0) {
                    var $button = $image_column[0].getElementsByClassName("button");
                    a3 = $button.length > 0 ? $button[0].outerHeight || 0 : 0;
                    a4 = parseInt($image_column[0].style.paddingTop) || 0;
                    a5 = parseInt($image_column[0].style.paddingBottom) || 0;
                }
                var img_col = a1 + a2 + a3 + a4 + a5;
                var h1 = $pages[i].height;
                var h2 = $wrapper[0].height;
                var pt = ($pages[i].offsetHeight - $wrapper[0].offsetHeight) / 2;
                pt = pt < 0 ? 0 : pt;
                if (img_col > h) {
                    $wrapper[0].style.height = "100%";
                    $wrapper[0].style.paddingTop = "0";
                } else {
                    $wrapper[0].style.height = "auto";
                    $wrapper[0].style.paddingTop = pt + "px";
                }
            }
        }

        if (!navigator.userAgent.toLowerCase().match(/(iphone|windows phone|android)/)) {
            document.getElementById("idea-menu").style.display = "none !important";
            if (rv > 9) {
                var fileref = document.createElement("link");
                fileref.setAttribute("rel", "stylesheet");
                fileref.setAttribute("type", "text/css");
                fileref.setAttribute("href", "@SfCms_user.StaticMethods.getBaseUrl(Url.Content("~"))/assets/css/anim.css");
                document.getElementsByTagName("head")[0].appendChild(fileref);
            }
        }
        var percVals = [
            @for (var i = 0; i < Model.beneficiary.list.Count; i++)
            {
                Model.project.id = Model.beneficiary.list[i].project_id;
                Model.project.get_data();
                
                if (Model.project.active)
                {
                    String p = Model.project.support_percent.ToString().Replace(",", ".") + (i + 1 != Model.beneficiary.list.Count ? "," : "");
                    @p;
                }
            }
        ];
    </script>

    <script type="text/javascript" src="~/assets/js/jquery.waypoints.min.js"></script>
    <script type="text/javascript" src="~/assets/js/jquery.easing.1.3.js"></script>
    <script type="text/javascript" src="~/assets/js/unslider.min.js"></script>
    <script type="text/javascript" src="~/assets/js/jquery.countTo.js"></script>
    <script type="text/javascript" src="~/assets/js/main.js"></script>
</body>
</html>

SfCms_user/Views/Shared/News.cshtml
@model SfCms_model.class_pattern

<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewContext.RouteData.Values["controller"] | Mentor - Gdański Program Stypendialny</title>
    <meta content="@ViewContext.RouteData.Values["controller"] | Mentor - gdański program stypendialny" name="description">
    <meta property="og:title" content="@ViewContext.RouteData.Values["controller"] | Mentor - Gdański Program Stypendialny">

    @{Html.RenderPartial("Header");}

    <link rel="stylesheet" href="~/assets/css/style_news.css" type="text/css">
    <link rel="stylesheet" href="~/assets/css/style_news_media.css" type="text/css">
</head>
<body>

    @RenderBody()

    @{Html.RenderPartial("Footer");}

    <script type="text/javascript" src="~/assets/js/jquery.fancybox.js"></script>
    <script type="text/javascript" src="~/assets/js/jquery.mousewheel-3.0.6.pack.js"></script>
    <script type="text/javascript" src="~/assets/js/jquery.fancybox.js"></script>
    <script type="text/javascript">
        var articles,
            style,
            min_h = 170;

        $(document).ready(function () {
            articles = $('.article');

            $('.fancybox').fancybox({
                type: 'image',
                openEffect: 'none',
                closeEffect: 'none',
                helpers: {
                    title: { type: 'inside' }
                }
            });

            adjustContentPosition();
            if (window.location.hash.length) {
                $(window.location.hash + ' .content').toggleClass('expanded');
                $(window.location.hash + ' .more-wrapper').toggleClass('translated');
            }

            $('.more').click(function () {
                $('.content', $(this).parent()).toggleClass('expanded');
                $('.more-wrapper', this).toggleClass('translated');
            });
        });

        $(window).resize(adjustContentPosition);
        $(window).load(adjustContentPosition);

        function adjustContentPosition() {
            if (style !== undefined)
                style.remove();
            var styleContent = '';
            articles.each(function () {
                h = $('.content .box', this).height();
                if (h <= min_h) {
                    $('.more-wrapper', this).hide();
                } else {
                    $('.more-wrapper', this).show();
                }
                styleContent += "#" + $(this).attr('id') + " .content.expanded {max-height:" + (h > min_h ? h + "px" : 'none') + ";}"
            });
            style = $("<style />", {
                id: 'articleHeightStyle',
                type: 'text/css',
                html: styleContent
            });
            style.appendTo('head');
        }
    </script>

</body>
</html>

SfCms_user/Views/Shared/_partial_form_login_info.cshtml
@model SfCms_model.class_pattern

<div style="text-align:center;">
    zalogowany...
    <br /><br />
    <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
</div>
        